import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import Navbar from "../components/Navbar";

export default function SharePage() {
  const { id } = useParams();
  const [results, setResults] = useState(null);

  useEffect(() => {
    try {
      const saved = localStorage.getItem(`share_${id}`);
      if (saved) setResults(JSON.parse(saved));
    } catch {
      // ignore
    }
  }, [id]);

  if (!results) {
    return (
      <div style={{ minHeight: "100vh", background: "#060816", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <Navbar />
        <div style={{ textAlign: "center" }}>
          <p style={{ color: "rgba(255,255,255,0.5)", marginBottom: 20 }}>Report not found or expired.</p>
          <Link to="/">
            <button style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)", color: "white", border: "none", borderRadius: 10, padding: "12px 24px", fontWeight: 700, cursor: "pointer" }}>
              Go Home
            </button>
          </Link>
        </div>
      </div>
    );
  }

  const { formData } = results;
  const totalMonthly = formData.rows.reduce((sum, r) => {
    return sum + (parseFloat(r.monthlySpend) || 0) * (parseInt(r.seats) || 1);
  }, 0);
  const totalAnnual = totalMonthly * 12;

  return (
    <div style={{ minHeight: "100vh", background: "#060816" }}>
      <Navbar />
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "120px 24px 80px" }}>
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div
            style={{
              background: "rgba(99,102,241,0.08)",
              border: "1px solid rgba(99,102,241,0.2)",
              borderRadius: 8,
              padding: "10px 16px",
              marginBottom: 32,
              fontSize: 13,
              color: "#a5b4fc",
            }}
          >
            📊 Shared AI Spend Report · Generated by SpendPilot
          </div>

          <h1 style={{ fontSize: "clamp(24px, 4vw, 36px)", fontWeight: 800, letterSpacing: "-0.8px", color: "white", marginBottom: 8 }}>
            AI Spend Audit Report
          </h1>
          <p style={{ color: "rgba(255,255,255,0.45)", fontSize: 14, marginBottom: 36 }}>
            Team: {formData.teamSize} people · Use case: {formData.useCase}
          </p>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 32 }}>
            {[
              { label: "Monthly spend", value: `$${totalMonthly.toFixed(0)}` },
              { label: "Annual spend", value: `$${totalAnnual.toFixed(0)}` },
            ].map((c) => (
              <div key={c.label} style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, padding: "20px", textAlign: "center" }}>
                <div style={{ fontSize: 26, fontWeight: 800, color: "white" }}>{c.value}</div>
                <div style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", marginTop: 4 }}>{c.label}</div>
              </div>
            ))}
          </div>

          <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 14, padding: 24, marginBottom: 32 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, color: "white", marginBottom: 16 }}>Tools audited</h3>
            {formData.rows.map((row) => (
              <div key={row.id} style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
                <span style={{ color: "white", fontSize: 14 }}>{row.tool} <span style={{ color: "rgba(255,255,255,0.4)" }}>({row.plan})</span></span>
                <span style={{ color: "rgba(255,255,255,0.6)", fontSize: 14 }}>
                  ${((parseFloat(row.monthlySpend) || 0) * (parseInt(row.seats) || 1)).toFixed(0)}/mo
                </span>
              </div>
            ))}
          </div>

          <Link to="/">
            <button style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)", color: "white", border: "none", borderRadius: 10, padding: "12px 24px", fontSize: 14, fontWeight: 700, cursor: "pointer" }}>
              Run your own audit →
            </button>
          </Link>
        </motion.div>
      </div>
    </div>
  );
}
